In [ ]:
#name:rathod dhruvi r.
#enrollment no:216270307090
#Practical No.6: Write a Pandas program to implement following operation 
#to convert a NumPy array to a Pandas series

import pandas as pd 
import numpy as np
ser = pd.Series() 
print("Pandas Series: ", ser) 
# simple array 
data = np.array(['h', 'a', 'r', 'e', 's']) 
ser = pd.Series(data) 
print("Pandas Series:\n", ser)

In [ ]:
#name:rathod dhruvi r.
#enrollment no:216270307090
#Practical No.6: Write a Pandas program to implement following operation 
#to convert the first column of a DataFrame as a Series
import pandas as pd 
import numpy as np
xy = pd.DataFrame() 
print(xy)
xy = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],}) 
print("Dataframe:")
print(xy)

In [ ]:
#name:rathod dhruvi r.
#enrollment no:216270307090
#Practical No.6: Write a Pandas program to implement following operation 
#to create the mean and standard deviation of the data of a given Series
import pandas as pd
import numpy as np
s = pd.Series(data = [2, 4, 5, 6, 7, 8, 9, 5, 3])
print(s.mean())
print(s.std())

In [ ]:
#name:rathod dhruvi r.
#enrollment no:216270307090
#Practical No.6: Write a Pandas program to implement following operation 
#to sort a given Series
import pandas as pd
import numpy as np
sr = pd.Series([5,2,3,7,5,6])
print(sr)
print(sr.sort_values(ascending=True))